server:
  port: 8080
spring:
  application:
    name: POCBankService
  datasource:
    url: jdbc:mysql://localhost:3306/reborn?useSSL=false&serverTimezone=UTC
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 2222
  flyway:
    enabled: true
    locations: classpath:db/migration
    default-schema: reborn
  #don't forgot start kafka. If using ubuntu or others server.
  ##sudo service redis-server start
  ##sudo service redis-server down
  redis:
    host: localhost
    port: 6379
#    password: ""
#    timeout: 2000
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  api:
    base-url: https://external-service.company.com
batch:
  schedule:
    cron: "0 0/1 * * * ?"
jwt:
  secret: 5ff4b0c9b2a356bd294ff36829610718dc053cd1fb66349f353f25d1cf7ce0697792f7352652ec46ea95f5875d93ae5e36e3c1b7d2eccf151aef99d0ac56ca2b